export const products = [
	{
		id: 1,
		img: '../img/bolos/60-anos.jpg',
		name: 'BOLOS',
		descricao: 'Bolo 60 anos',
	},
	{
		id: 2,
		img: '../img/bolos/bodas.jpg',
		name: 'BOLOS',
        descricao: 'Bolo bodas 50 anos',
	},
	{
		id: 3,
		img: '../img/bolos/bolo-flores.jpg',
		name: 'BOLOS',
        descricao: 'Bolo com elementos florais',
	},
	{
		id: 4,
		img: '../img/bolos/cross-fit.jpg',
		name: 'BOLOS',
        descricao: 'Bolo cross fit com figura 3D',
	},
	{
		id: 5,
		img: '../img/bolos/stitch.jpg',
		name: 'BOLOS',
        descricao: 'Bolo com boneco Stitch',
	},
	{
		id: 6,
		img: '../img/sobremesas/chinfon.jpg',
		name: 'SOBREMESAS',
        descricao: 'Tarte de coco merengado',
	},
	{
		id: 7,
		img: '../img/sobremesas/mouse.jpg',
		name: 'SOBREMESAS',
        descricao: 'Mouse de chocolate',
	},
	{
		id: 8,
		img: '../img/sobremesas/pao-de-lo.jpg',
		name: 'SOBREMESAS',
        descricao: 'Pão de ló',
	},
	{
		id: 9,
		img: '../img/sobremesas/tarte-abobora.jpg',
		name: 'SOBREMESAS',
        descricao: 'Tarte de abobora',
	},
	{
		id: 10,
		img: '../img/sobremesas/tarte-nata.jpg',
		name: 'SOBREMESAS',
        descricao: 'Tarte e pasteis de nata',
	},
	{
		id: 11,
		img: '../img/frutas/ananas-kiwi.jpg',
		name: 'FRUTAS',
        descricao: 'Ananás e kiwi',
	},
	{
		id: 12,
		img: '../img/frutas/espetada-frutas.jpg',
		name: 'FRUTAS',
        descricao: 'Espetada de frutas',
	},
    {
		id: 13,
		img: '../img/frutas/mamao.jpg',
		name: 'FRUTAS',
        descricao: 'Mamão',
	},
    {
		id: 14,
		img: '../img/frutas/morangos.jpg',
		name: 'FRUTAS',
        descricao: 'Morangos',
	},
    {
		id: 15,
		img: '../img/frutas/varias.jpg',
		name: 'FRUTAS',
        descricao: 'Fruta variada',
	},
    {
		id: 16,
		img: '../img/pratosQ/bacalhau-broa.jpg',
		name: 'PRATOS-QUENTES',
        descricao: 'Bacalhau com Broa',
	},
    {
		id: 17,
		img: '../img/pratosQ/bacalhau-espiritual.jpg',
		name: 'PRATOS-QUENTES',
        descricao: 'Bacalhau Espiritual',
	},
    {
		id: 18,
		img: '../img/pratosQ/bacalhau.jpg',
		name: 'PRATOS-QUENTES',
        descricao: 'Bacalhau à Brás',
	},
    {
		id: 19,
		img: '../img/pratosQ/camarao.jpg',
		name: 'PRATOS-QUENTES',
        descricao: 'Camarão em molho de manteiga',
	},
    {
		id: 20,
		img: '../img/pratosQ/varios.jpg',
		name: 'PRATOS-QUENTES',
        descricao: 'Vários pratos',
	},
    {
		id: 21,
		img: '../img/tapas/bola.jpg',
		name: 'TAPAS-PETISCOS',
        descricao: 'Bola de Carne',
	},
    {
		id: 22,
		img: '../img/tapas/camarao.jpg',
		name: 'TAPAS-PETISCOS',
        descricao: 'Camarão cozido',
	},
    {
		id: 23,
		img: '../img/tapas/fritos.jpg',
		name: 'TAPAS-PETISCOS',
        descricao: 'Fritos variados',
	},
    {
		id: 24,
		img: '../img/tapas/quiche.jpg',
		name: 'TAPAS-PETISCOS',
        descricao: 'Quiche e sortido de fritos',
	},
    {
		id: 25,
		img: '../img/tapas/tabua-enchidos.jpg',
		name: 'TAPAS-PETISCOS',
        descricao: 'Tábua de enchidos',
	},

];

export default products;